"""Sphinx configuration for the gecko-docs documentation.

`.readthedocs.yaml` builds from this file. Configuration mirrors
raven-docs' `docs/conf.py` (same extensions, same theme, same generator
pattern), since gecko-docs tracks the same house style and the two sites
should behave the same way for a reader moving between them.
"""

from __future__ import annotations

project = "GECKO"
copyright = "SysBioChalmers"
author = "Chen, Gustafsson, Tafur Rangel et al."

extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
    # GECKO's introduction covers the kcat/MW stoichiometry math with LaTeX
    # ($$ ... $$); dollarmath (below) only parses that into math nodes, this
    # extension is what actually renders them via MathJax. RAVEN's docs have
    # no equations, so raven-docs' conf.py doesn't need it.
    "sphinx.ext.mathjax",
]

source_suffix = {".md": "markdown"}
root_doc = "index"

myst_enable_extensions = [
    "colon_fence",  # the ::: directive spelling used throughout this site
    "deflist",
    "attrs_inline",
    "dollarmath",
]
myst_heading_anchors = 4

exclude_patterns = [
    "_build",
    "conf.py",
    # Generated by scripts/gen_api_pages_sphinx.py at build time, present only
    # after that script has run once.
]

html_theme = "pydata_sphinx_theme"
# pydata-sphinx-theme's own template appends "-- {{ project }}" to whatever
# html_title is, so "GECKO" here would double up with project = "GECKO"
# above into a duplicated page title.
html_title = "GECKO documentation"
html_favicon = "assets/gecko-icon-green.png"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
# The "view source" link points at this generated MyST file, not anything a
# reader can act on the way an edit-on-GitHub link would.
html_show_sourcelink = False

html_theme_options = {
    "show_nav_level": 1,
    "navigation_depth": 4,
    # Only the active path expands; everything else stays collapsed until
    # clicked, rather than the whole tree opening at once.
    "collapse_navigation": True,
    "show_toc_level": 2,
    "github_url": "https://github.com/SysBioChalmers/GECKO",
    "use_edit_page_button": False,
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "logo": {
        "image_light": "assets/gecko-icon-green.png",
        "image_dark": "assets/gecko-icon-white.png",
        "text": "GECKO",
    },
    "announcement": (
        "This site documents GECKO <strong>4.0.0b1</strong> "
        "(MATLAB and Python), a pre-release version. The API may still "
        "change before the stable 4.0.0 release."
    ),
}

html_context = {
    "default_mode": "auto",
}


def setup(app):
    """Run the API-reference generator before Sphinx reads the source tree.

    Statically extracts full docstrings for both GECKO (MATLAB, via direct
    help-block parsing) and geckopy (Python, via griffe used standalone) and
    writes plain MyST pages -- there is no maintained Sphinx equivalent of
    mkdocstrings / mkdocstrings-matlab (both MkDocs-only live-rendering
    plugins), the same conclusion raven-docs reached for RAVEN / raven-toolbox.
    """
    from pathlib import Path
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
    import gen_api_pages_sphinx

    gen_api_pages_sphinx.generate(Path(__file__).resolve().parent)
